language: node_js

node_js:
  - "8"
  - "9"

cache:
  directories:
    - "node_modules"
    - "semantic"

install:
  - npm install
  - npm run build-semantic

script:
  - ng build --progress=false

notifications:
  email: false
